### ISSUE TITLE
update license and contact email

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/hmis-bulk-api#5]
![Screenshot from 2019-03-21 10-10-37](https://user-images.githubusercontent.com/4115079/54759553-b2fb5600-4bc4-11e9-9265-4ac0b15e9bce.png)

**Comment by logicsandeep** [comment]
Fixed the license and contact email.
https://github.com/hmis-api/hmis-bulk-api/commit/11b3fb2709d396a9914851a75420b5a1afe4ed81
